=== peekhovsky/epam-javase-2018/task4/src/main/resources/xml/medicines.xsd
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'
           elementFormDefault="qualified">

    <xs:element name="medicines">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="medicine" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="medicine">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="analogs" minOccurs="0"/>
                <xs:element ref="versions"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="pharm" type="xs:string" use="required"/>
            <xs:attribute ref="group" default="other"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="analogs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="analog" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="analog">
        <xs:complexType>
            <xs:attribute name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="versions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="version" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="version">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="company" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="type" default="pills"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="certificate"/>
                <xs:element ref="package"/>
                <xs:element ref="dosage"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="certificate">
        <xs:complexType>
            <xs:attribute name="num" type="xs:unsignedLong" use="required"/>
            <xs:attribute name="issueDate" type="xs:date"/>
            <xs:attribute name="expireDate" type="xs:date" use="required"/>
            <xs:attribute name="regOrganisation" type="xs:string"
                          use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="package">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string"
                          use="required"/>
            <xs:attribute name="quantity" type="xs:unsignedInt"
                          use="required"/>
            <xs:attribute name="price" type="xs:unsignedLong"
                          use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="dosage">
        <xs:complexType>
            <xs:attribute name="valuePerDay" type="xs:unsignedInt"
                          use="required"/>
            <xs:attribute name="periodDays" type="xs:unsignedInt"
                          use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:attribute name="group">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="painkillers"/>
                <xs:enumeration value="antibiotics"/>
                <xs:enumeration value="vitamins"/>
                <xs:enumeration value="drops"/>
                <xs:enumeration value="other"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="powder"/>
                <xs:enumeration value="pills"/>
                <xs:enumeration value="capsule"/>
                <xs:enumeration value="light"/>
                <xs:enumeration value="ointment"/>
                <xs:enumeration value="other"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
</xs:schema>

=== peekhovsky/epam-javase-2018/task4/src/main/resources/xml/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="medicines.xsd">
    <!-- Aspirin -->
    <medicine id="1" name="aspirin" pharm="Pharmacare" group="painkillers">
        <analogs>
            <analog name="asafen"/>
            <analog name="acetylsalicylic acid"/>
        </analogs>

        <versions>
            <version>
                <company name="Borisov Med">
                    <certificate num="112233" issueDate="2018-11-12"
                                 expireDate="2018-11-12"
                                 regOrganisation="Belorussian pharmacy"/>
                    <package type="box" quantity="10" price="10"/>
                    <dosage valuePerDay="2" periodDays="14"/>
                </company>
                <company name="Pharmacare">
                    <certificate num="223344" issueDate="2008-12-12"
                                 expireDate="2020-04-21"
                                 regOrganisation="US DRUGS"/>
                    <package type="box" quantity="5" price="50"/>
                    <dosage valuePerDay="1" periodDays="6"/>
                </company>
            </version>
            <version type="powder">
                <company name="Borisov Med">
                    <certificate num="445566" issueDate="1999-11-12"
                                 expireDate="2025-11-12"
                                 regOrganisation="Belorussian pharmacy"/>
                    <package type="box" quantity="2" price="15"/>
                    <dosage valuePerDay="1" periodDays="14"/>
                </company>
            </version>
        </versions>
    </medicine>

    <!-- Adicef -->
    <medicine id="2" name="adicef" pharm="Pharmacare" group="antibiotics">
        <analogs>
            <analog name="wd"/>
        </analogs>
        <versions>
            <version type="pills">
                <company name="Pharmacare">
                    <certificate num="665544" expireDate="2015-03-04"
                                 regOrganisation="US DRUGS"/>
                    <package type="box" quantity="10" price="100"/>
                    <dosage valuePerDay="1" periodDays="30"/>
                </company>
            </version>
        </versions>
    </medicine>

    <!-- Asafen -->
    <medicine id="3" name="asafen" pharm="Pharmacare" group="painkillers">
        <analogs>
            <analog name="aspirin"/>
            <analog name="acetylsalicylic acid"/>
        </analogs>
        <versions>
            <version type="powder">
                <company name="Pharmacare">
                    <certificate num="998877" issueDate="2005-04-05"
                                 expireDate="2019-11-15"
                                 regOrganisation="Israel Pharmacy Dept."/>
                    <package type="flask" quantity="50" price="200"/>
                    <dosage valuePerDay="3" periodDays="14"/>
                </company>
            </version>
        </versions>
    </medicine>

    <!-- Acetylsalicylic acid -->
    <medicine id="4" name="acetylsalicylic acid" pharm="Borisov Med"
              group="painkillers">
        <analogs>
            <analog name="aspirin"/>
            <analog name="asafen"/>
        </analogs>

        <versions>
            <version type="powder">
                <company name="Borisov Med">
                    <certificate num="554321" issueDate="2017-12-30"
                                 expireDate="2024-12-30"
                                 regOrganisation="Belorussian pharmacy"/>
                    <package type="flask" quantity="200" price="30"/>
                    <dosage valuePerDay="10" periodDays="60"/>
                </company>
            </version>
        </versions>
    </medicine>

    <medicine id="5" name="rainbow men's vitamins" pharm="Rainbow"
              group="vitamins">
        <analogs>
            <analog name="smarty men's vitamins"/>
        </analogs>

        <versions>
            <version type="pills">
                <company name="Rainbow">
                    <certificate num="221144" issueDate="2017-03-03"
                                 expireDate="2026-03-03"
                                 regOrganisation="US DRUGS"/>
                    <package type="box" quantity="100" price="210"/>
                    <dosage valuePerDay="3" periodDays="30"/>
                </company>
                <company name="BERLIN-CHEMIE">
                    <certificate num="3144" issueDate="2017-05-03"
                                 expireDate="2026-05-03"
                                 regOrganisation="German pharmacy control dept."/>
                    <package type="box" quantity="200" price="210"/>
                    <dosage valuePerDay="6" periodDays="30"/>
                </company>
            </version>
        </versions>
    </medicine>


    <medicine id="6" name="smarty men's vitamins" pharm="Smarty"
              group="vitamins">
        <analogs>
            <analog name="rainbow men's vitamins"/>
        </analogs>

        <versions>
            <version type="capsule">
                <company name="Smarty">
                    <certificate num="221344" issueDate="2007-09-11"
                                 expireDate="2027-09-11"
                                 regOrganisation="US DRUGS"/>
                    <package type="flask" quantity="100" price="150"/>
                    <dosage valuePerDay="2" periodDays="60"/>
                </company>
            </version>
        </versions>
    </medicine>

    <medicine id="7" name="total 2" pharm="Dailies" group="drops">
        <analogs>
            <analog name="dry eye"/>
        </analogs>
        <versions>
            <version type="other">
                <company name="Dailies">
                    <certificate num="343434" issueDate="2009-10-10"
                                 expireDate="2020-10-10"
                                 regOrganisation="UK Pharmacy"/>
                    <package type="flask" quantity="250" price="150"/>
                    <dosage valuePerDay="3" periodDays="60"/>
                </company>
            </version>
        </versions>
    </medicine>

    <medicine id="8" name="dry eye" pharm="Visine" group="drops">
        <analogs>
            <analog name="total 2"/>
        </analogs>
        <versions>
            <version type="light">
                <company name="Visine">
                    <certificate num="3232111" issueDate="2018-12-14"
                                 expireDate="2038-12-14"
                                 regOrganisation="UK Pharmacy"/>
                    <package type="flask" quantity="100" price="150"/>
                    <dosage valuePerDay="2" periodDays="60"/>
                </company>
                <company name="Rainbow">
                    <certificate num="2000044" issueDate="2017-11-11"
                                 expireDate="2027-11-11"
                                 regOrganisation="US DRUGS"/>
                    <package type="flask" quantity="100" price="150"/>
                    <dosage valuePerDay="1" periodDays="120"/>
                </company>
            </version>
        </versions>
    </medicine>
    <medicine id="9" name="anti-herpes" pharm="Zovirax" group="antibiotics">
        <versions>
            <version type="ointment">
                <company name="Smarty">
                    <certificate num="221344" issueDate="2007-09-11"
                                 expireDate="2027-09-11"
                                 regOrganisation="US DRUGS"/>
                    <package type="tube" quantity="150" price="110"/>
                    <dosage valuePerDay="1" periodDays="30"/>
                </company>
            </version>
        </versions>
    </medicine>
    <medicine id="9" name="dry eye" pharm="Visine" group="drops">
        <analogs>
            <analog name="total 2"/>
            <analog name="dry eye"/>
        </analogs>
        <versions>
            <version>
                <company name="US Pharmacy">
                    <certificate num="3232111" issueDate="2018-12-14"
                                 expireDate="2038-12-14"
                                 regOrganisation="UK Pharmacy"/>
                    <package type="flask" quantity="100" price="150"/>
                    <dosage valuePerDay="2" periodDays="60"/>
                </company>
                <company name="Rainbow">
                    <certificate num="2000044" issueDate="2010-11-11"
                                 expireDate="2029-11-11"
                                 regOrganisation="US DRUGS"/>
                    <package type="tube" quantity="100" price="150"/>
                    <dosage valuePerDay="1" periodDays="120"/>
                </company>
            </version>
            <version type="powder">
                <company name="ABC">
                    <certificate num="9876543" expireDate="2014-12-12"
                                 regOrganisation="2028-12-12"/>
                    <package type="flask" quantity="100" price="120"/>
                    <dosage valuePerDay="2" periodDays="30"/>
                </company>
            </version>
        </versions>
    </medicine>
    <medicine id="10" name="anti-herpes" pharm="Zovirax" group="antibiotics">
        <versions>
            <version type="ointment">
                <company name="Smarty">
                    <certificate num="221344" issueDate="2007-09-11"
                                 expireDate="2027-09-11"
                                 regOrganisation="US DRUGS"/>
                    <package type="tube" quantity="150" price="110"/>
                    <dosage valuePerDay="1" periodDays="30"/>
                </company>
            </version>
        </versions>
    </medicine>
